[package]
name = "FusionSwapAptos"
version = "1.0.0"
authors = ["Fusion Swap Team"]

[addresses]
fusion_swap_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }

[dev-dependencies]
